FROM mysql:5.7

#ENV MYSQL_DATA_DIR=/var/lib/mysql \
#    MYSQL_LOG_DIR=/var/log/mysql
#PERMISSAO DE EXECUÇÃO    
RUN chmod -R +x docker-entrypoint-initdb.d    
#COPY scripts/init.sql docker-entrypoint-initdb.d/init.sql
#RUN chmod -R 775 /docker-entrypoint-initdb.d
